# Generated by Django 4.2.6 on 2024-01-20 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apostilas', '0002_viewapostila'),
    ]

    operations = [
        migrations.AddField(
            model_name='apostila',
            name='tags',
            field=models.CharField(default='', max_length=100),
        ),
    ]
